-- INSERT vendedores
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Missy', 'Eccles', 31, '3907 Karstens Avenue', 4);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Harry', 'Kingzett', 50, '736 Anniversary Point', 5);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Bartram', 'Ciottoi', 50, '32712 Longview Circle', 8);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Darcie', 'Abrahams', 49, '161 Butterfield Way', 6);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Joyann', 'Tennison', 22, '6187 Superior Crossing', 8);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Cosetta', 'Press', 41, '62610 Forest Trail', 2);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Cloris', 'Freen', 26, '96421 Basil Point', 7);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Loree', 'Blenkensop', 57, '57780 Superior Park', 2);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Velvet', 'Wagg', 30, '46 Marquette Circle', 9);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Lorrayne', 'Vogt', 49, '380 Veith Pass', 10);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Emmit', 'Torrese', 57, '64 Burning Wood Avenue', 9);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Johanna', 'Knobell', 25, '2 Debs Way', 8);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Winn', 'Charlick', 53, '6455 Mayfield Court', 10);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Mal', 'Tubridy', 44, '947 Ridge Oak Hill', 3);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Ingaborg', 'Louden', 41, '57451 Melrose Court', 8);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Xerxes', 'McCurtain', 48, '894 Division Street', 7);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Elicia', 'Rogliero', 26, '7396 Scott Plaza', 7);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Veronique', 'Beran', 34, '28263 Porter Terrace', 6);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Mufi', 'Camier', 51, '74731 Village Parkway', 9);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Wallis', 'Garber', 28, '28 Pawling Avenue', 8);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Eamon', 'Spurgin', 57, '0700 Eagan Alley', 1);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Rurik', 'Phillipson', 22, '1 Portage Parkway', 10);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Randall', 'Kielt', 57, '2900 Forest Dale Park', 8);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Rene', 'Kelston', 32, '23630 Barby Lane', 9);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Bendick', 'Tripe', 20, '70 Oriole Plaza', 2);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Anabelle', 'Leek', 54, '68 Stang Drive', 1);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Robinette', 'Silverthorn', 24, '8667 Barby Lane', 3);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Jocelyn', 'Howsan', 26, '6606 Bultman Junction', 7);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Reinaldo', 'Filip', 38, '7 Hagan Trail', 3);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Rosette', 'Cheevers', 34, '4451 Mayfield Terrace', 4);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Levey', 'Torrent', 51, '6331 Luster Pass', 1);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Wendel', 'Eacott', 20, '15 Arizona Plaza', 1);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Kettie', 'Gutowski', 54, '2980 Pond Lane', 9);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Felisha', 'Barsham', 49, '47 Ruskin Park', 1);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Gilberte', 'Purtell', 58, '1297 Buhler Circle', 1);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Gay', 'Dehn', 34, '722 Charing Cross Alley', 3);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Roanne', 'Manoelli', 27, '48 Vidon Park', 10);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Angeline', 'Dell ''Orto', 37, '85242 Duke Road', 6);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Grove', 'Haldene', 21, '532 Corben Circle', 5);
insert into vendedores (nombre, apellido, edad, direccion, id_sucursal) values ('Caressa', 'Franek', 20, '2424 Bultman Plaza', 6);
