-- INSERT Automoviles
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Dodge', 'Ram Wagon B150', 1994, 'Indigo', 'Diesel', 'Manual', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Subaru', 'Legacy', 1991, 'Aquamarine', 'Nafta', 'Automatico', 2);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Dodge', 'Ram 2500', 2009, 'Green', 'Electrico', 'Automatico', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Toyota', 'Prius', 2004, 'Goldenrod', 'Nafta', 'Automatico', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Jaguar', 'XJ Series', 2001, 'Yellow', 'Nafta', 'Manual', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Volkswagen', 'Quantum', 1984, 'Khaki', 'Nafta', 'Manual', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mitsubishi', 'Lancer', 2003, 'Teal', 'Nafta', 'Manual', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Buick', 'Park Avenue', 2003, 'Green', 'Electrico', 'Automatico', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Pontiac', 'Grand Prix', 1974, 'Khaki', 'Electrico', 'Automatico', 5);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Oldsmobile', 'Bravada', 2000, 'Orange', 'Diesel', 'Manual', 2);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Volkswagen', 'Passat', 1988, 'Indigo', 'Diesel', 'Manual', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Volvo', 'V50', 2011, 'Green', 'Diesel', 'Manual', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Daewoo', 'Leganza', 2002, 'Yellow', 'Diesel', 'Manual', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Nissan', 'Versa', 2011, 'Crimson', 'Diesel', 'Automatico', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Buick', 'Riviera', 1992, 'Maroon', 'Nafta', 'Automatico', 6);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Honda', 'Civic', 2004, 'Pink', 'Nafta', 'Automatico', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('BMW', 'X5', 2013, 'Yellow', 'Electrico', 'Automatico', 7);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Plymouth', 'Sundance', 1992, 'Crimson', 'Diesel', 'Automatico', 6);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Audi', 'A8', 2001, 'Yellow', 'Nafta', 'Manual', 6);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Lexus', 'GX', 2008, 'Aquamarine', 'Nafta', 'Automatico', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Cadillac', 'Fleetwood', 1996, 'Mauv', 'Diesel', 'Manual', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Ford', 'F-Series Super Duty', 2011, 'Aquamarine', 'Electrico', 'Manual', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chevrolet', 'Blazer', 1992, 'Orange', 'Electrico', 'Manual', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mitsubishi', 'Pajero', 1988, 'Teal', 'Electrico', 'Manual', 5);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Ford', 'ZX2', 2001, 'Blue', 'Diesel', 'Automatico', 2);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Plymouth', 'Colt Vista', 1993, 'Maroon', 'Electrico', 'Manual', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Lexus', 'LS', 1991, 'Crimson', 'Electrico', 'Automatico', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Dodge', 'Ram Van 2500', 1995, 'Turquoise', 'Diesel', 'Automatico', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Volvo', 'XC70', 2003, 'Crimson', 'Electrico', 'Manual', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Suzuki', 'X-90', 1996, 'Purple', 'Nafta', 'Manual', 3);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chrysler', 'Town & Country', 1995, 'Khaki', 'Diesel', 'Automatico', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mercury', 'Topaz', 1990, 'Orange', 'Electrico', 'Automatico', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mercedes-Benz', 'SLK-Class', 2003, 'Aquamarine', 'Nafta', 'Manual', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Pontiac', 'Sunbird', 1989, 'Aquamarine', 'Diesel', 'Automatico', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Land Rover', 'Range Rover', 2010, 'Yellow', 'Electrico', 'Manual', 6);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Lexus', 'CT', 2011, 'Pink', 'Diesel', 'Automatico', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Ford', 'Windstar', 1999, 'Turquoise', 'Electrico', 'Automatico', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Ford', 'Thunderbird', 1986, 'Purple', 'Electrico', 'Automatico', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Honda', 'Civic', 1994, 'Red', 'Nafta', 'Manual', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Lincoln', 'Navigator L', 2010, 'Indigo', 'Diesel', 'Manual', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Toyota', 'Corolla', 1998, 'Teal', 'Electrico', 'Manual', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('BMW', '530', 2002, 'Teal', 'Diesel', 'Automatico', 3);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Lotus', 'Elan', 1993, 'Green', 'Diesel', 'Automatico', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Hyundai', 'Entourage', 2007, 'Crimson', 'Electrico', 'Manual', 6);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mitsubishi', 'GTO', 1991, 'Puce', 'Electrico', 'Automatico', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Ford', 'Fusion', 2010, 'Khaki', 'Diesel', 'Manual', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('GMC', 'Savana', 2007, 'Red', 'Nafta', 'Automatico', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chrysler', 'Cirrus', 2000, 'Puce', 'Diesel', 'Automatico', 6);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Scion', 'xB', 2009, 'Khaki', 'Diesel', 'Automatico', 3);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Infiniti', 'Q', 2002, 'Green', 'Electrico', 'Manual', 3);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Nissan', 'Maxima', 2001, 'Orange', 'Nafta', 'Manual', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Pontiac', 'Firefly', 1990, 'Violet', 'Nafta', 'Manual', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Land Rover', 'Discovery', 2006, 'Pink', 'Nafta', 'Manual', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chevrolet', 'Express 1500', 2011, 'Crimson', 'Electrico', 'Manual', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Land Rover', 'Range Rover', 1995, 'Puce', 'Diesel', 'Automatico', 6);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Volkswagen', 'New Beetle', 2003, 'Aquamarine', 'Nafta', 'Manual', 7);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Land Rover', 'Discovery', 2011, 'Aquamarine', 'Nafta', 'Manual', 7);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Ford', 'Club Wagon', 1996, 'Red', 'Nafta', 'Automatico', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Lincoln', 'MKS', 2012, 'Maroon', 'Electrico', 'Automatico', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mercedes-Benz', 'R-Class', 2009, 'Yellow', 'Electrico', 'Manual', 7);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Ford', 'Expedition', 2005, 'Khaki', 'Diesel', 'Automatico', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chevrolet', '3500', 2000, 'Violet', 'Nafta', 'Manual', 5);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Isuzu', 'Hombre', 2000, 'Maroon', 'Diesel', 'Manual', 6);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chevrolet', 'Aveo', 2009, 'Orange', 'Electrico', 'Manual', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Audi', 'A6', 2004, 'Pink', 'Diesel', 'Automatico', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Cadillac', 'CTS', 2009, 'Blue', 'Diesel', 'Manual', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mercury', 'Villager', 1995, 'Mauv', 'Diesel', 'Automatico', 3);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Lexus', 'ES', 1991, 'Khaki', 'Electrico', 'Automatico', 2);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chevrolet', 'Express 2500', 2007, 'Purple', 'Diesel', 'Manual', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Honda', 'Fit', 2010, 'Khaki', 'Electrico', 'Automatico', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Lexus', 'HS', 2010, 'Indigo', 'Nafta', 'Automatico', 5);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mazda', 'Miata MX-5', 2011, 'Indigo', 'Electrico', 'Manual', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Volkswagen', 'Cabriolet', 2001, 'Yellow', 'Electrico', 'Automatico', 6);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chevrolet', '2500', 1995, 'Teal', 'Nafta', 'Automatico', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Audi', 'Allroad', 2005, 'Fuscia', 'Diesel', 'Automatico', 5);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mercedes-Benz', 'CL-Class', 2009, 'Blue', 'Electrico', 'Manual', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Land Rover', 'Range Rover', 2006, 'Yellow', 'Electrico', 'Automatico', 7);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Volvo', 'V70', 2007, 'Khaki', 'Nafta', 'Automatico', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Infiniti', 'G', 2000, 'Mauv', 'Diesel', 'Automatico', 3);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chrysler', 'Prowler', 2001, 'Goldenrod', 'Diesel', 'Manual', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chevrolet', 'Camaro', 1967, 'Green', 'Diesel', 'Manual', 7);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Ford', 'F350', 2000, 'Red', 'Diesel', 'Manual', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chrysler', '300M', 2002, 'Turquoise', 'Electrico', 'Manual', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mercury', 'Sable', 1998, 'Maroon', 'Nafta', 'Manual', 2);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mazda', 'B2600', 1989, 'Goldenrod', 'Diesel', 'Manual', 5);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Toyota', 'Paseo', 1995, 'Blue', 'Diesel', 'Manual', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Dodge', 'Ram 1500', 2005, 'Red', 'Diesel', 'Automatico', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Dodge', 'Grand Caravan', 2010, 'Pink', 'Nafta', 'Manual', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Porsche', 'Boxster', 1997, 'Indigo', 'Electrico', 'Automatico', 7);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chevrolet', 'G-Series 2500', 1996, 'Crimson', 'Nafta', 'Manual', 1);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Nissan', 'Frontier', 2012, 'Indigo', 'Nafta', 'Manual', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Honda', 'Pilot', 2003, 'Maroon', 'Electrico', 'Manual', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Ford', 'GT', 2006, 'Crimson', 'Nafta', 'Automatico', 5);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Chevrolet', 'Corvette', 1969, 'Puce', 'Diesel', 'Manual', 4);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Hyundai', 'Scoupe', 1992, 'Teal', 'Diesel', 'Automatico', 9);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Mitsubishi', 'Galant', 1996, 'Pink', 'Nafta', 'Manual', 10);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Volkswagen', 'New Beetle', 2010, 'Red', 'Nafta', 'Manual', 3);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Porsche', '928', 1989, 'Purple', 'Diesel', 'Automatico', 2);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Suzuki', 'Esteem', 2001, 'Khaki', 'Nafta', 'Manual', 8);
insert into automoviles (marca, modelo, anio, color, tipo_combustible, transmision, id_sucursal) values ('Maserati', 'GranSport', 2005, 'Purple', 'Nafta', 'Manual', 10);
